apiVersion: v2
appVersion: 1.2.3
description: Jellyfin Media Server
name: jellyfin
version: 1.6.0
type: application
home: https://jellyfin.org/
icon: https://jellyfin.org/images/logo.svg
keywords:
  - jellyfin
  - media
  - self-hosted
