name: Docs Update

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 0

    - name: Helm Docs GitHub Action
      uses: losisin/helm-docs-github-action@7b7955b018c87e10abf75fec0e8fe459556aec68 # v1.5.1
      with:
        git-push: true
        git-commit-message: "docs(charts): :memo: write updated reademe"

    - name: Push changes
      run: git push